# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.protos
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.protos\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x1e\n\rMovieSchedule\x12\r\n\x05movie\x18\x01 \x01(\t\"(\n\x08Schedule\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x0f\n\rEmptySchedule2a\n\x08Showtime\x12%\n\x0fGetMoviesByDate\x12\x05.Date\x1a\t.Schedule\"\x00\x12.\n\x08GetTimes\x12\x0e.EmptySchedule\x1a\x0e.MovieSchedule\"\x00\x30\x01\x62\x06proto3')



_DATE = DESCRIPTOR.message_types_by_name['Date']
_MOVIESCHEDULE = DESCRIPTOR.message_types_by_name['MovieSchedule']
_SCHEDULE = DESCRIPTOR.message_types_by_name['Schedule']
_EMPTYSCHEDULE = DESCRIPTOR.message_types_by_name['EmptySchedule']
Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

MovieSchedule = _reflection.GeneratedProtocolMessageType('MovieSchedule', (_message.Message,), {
  'DESCRIPTOR' : _MOVIESCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:MovieSchedule)
  })
_sym_db.RegisterMessage(MovieSchedule)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Schedule)
  })
_sym_db.RegisterMessage(Schedule)

EmptySchedule = _reflection.GeneratedProtocolMessageType('EmptySchedule', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYSCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:EmptySchedule)
  })
_sym_db.RegisterMessage(EmptySchedule)

_SHOWTIME = DESCRIPTOR.services_by_name['Showtime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATE._serialized_start=18
  _DATE._serialized_end=38
  _MOVIESCHEDULE._serialized_start=40
  _MOVIESCHEDULE._serialized_end=70
  _SCHEDULE._serialized_start=72
  _SCHEDULE._serialized_end=112
  _EMPTYSCHEDULE._serialized_start=114
  _EMPTYSCHEDULE._serialized_end=129
  _SHOWTIME._serialized_start=131
  _SHOWTIME._serialized_end=228
# @@protoc_insertion_point(module_scope)
