# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import base_pb2 as protos_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/user.proto\x1a\x11protos/base.proto\"A\n\x08UserItem\x12\x13\n\x02id\x18\x01 \x01(\x0b\x32\x07.UserID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nlastactive\x18\x03 \x01(\t\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t2Q\n\x04User\x12$\n\x0bGetAllUsers\x12\x06.Empty\x1a\t.UserItem\"\x00\x30\x01\x12#\n\x0bGetUserById\x12\x07.UserID\x1a\t.UserItem\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERITEM._serialized_start=40
  _USERITEM._serialized_end=105
  _USERID._serialized_start=107
  _USERID._serialized_end=127
  _USER._serialized_start=129
  _USER._serialized_end=210
# @@protoc_insertion_point(module_scope)
