# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2
import movie_pb2 as movie__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\x1a\nbase.proto\x1a\x0bmovie.proto\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"9\n\x08Schedule\x12\x13\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x05.Date\x12\x18\n\x06movies\x18\x02 \x03(\x0b\x32\x08.MovieID2S\n\x08Showtime\x12%\n\x0fGetMoviesByDate\x12\x05.Date\x1a\t.Schedule\"\x00\x12 \n\x08GetTimes\x12\x06.Empty\x1a\x08.MovieID\"\x00\x30\x01\x62\x06proto3')



_DATE = DESCRIPTOR.message_types_by_name['Date']
_SCHEDULE = DESCRIPTOR.message_types_by_name['Schedule']
Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), {
  'DESCRIPTOR' : _DATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Date)
  })
_sym_db.RegisterMessage(Date)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:Schedule)
  })
_sym_db.RegisterMessage(Schedule)

_SHOWTIME = DESCRIPTOR.services_by_name['Showtime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATE._serialized_start=43
  _DATE._serialized_end=63
  _SCHEDULE._serialized_start=65
  _SCHEDULE._serialized_end=122
  _SHOWTIME._serialized_start=124
  _SHOWTIME._serialized_end=207
# @@protoc_insertion_point(module_scope)
