# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/booking.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import base_pb2 as protos_dot_base__pb2
from protos import user_pb2 as protos_dot_user__pb2
from protos import showtime_pb2 as protos_dot_showtime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/booking.proto\x1a\x11protos/base.proto\x1a\x11protos/user.proto\x1a\x15protos/showtime.proto\"?\n\x0b\x42ookingData\x12\x17\n\x06userId\x18\x01 \x01(\x0b\x32\x07.UserID\x12\x17\n\x04\x64\x61te\x18\x02 \x03(\x0b\x32\t.Schedule2d\n\x07\x42ooking\x12*\n\x0eGetAllBookings\x12\x06.Empty\x1a\x0c.BookingData\"\x00\x30\x01\x12-\n\x12GetBookingByUserId\x12\x07.UserID\x1a\x0c.BookingData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.booking_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKINGDATA._serialized_start=85
  _BOOKINGDATA._serialized_end=148
  _BOOKING._serialized_start=150
  _BOOKING._serialized_end=250
# @@protoc_insertion_point(module_scope)
